### ISSUE TITLE
Android artifacts for 0.8.0 weren't published

### ISSUE THREAD

**Issue by tadfisher** [chRyNaN/serialization-parcelable#8]
Looking at the [Maven repository index](https://repo.repsy.io/mvn/chrynan/public/com/chrynan/parcelable/), the following artifacts weren't published for version 0.8.0:

- [parcelable-compose-android-debug/](https://repo.repsy.io/mvn/chrynan/public/com/chrynan/parcelable/parcelable-compose-android-debug/)
- [parcelable-compose-android/](https://repo.repsy.io/mvn/chrynan/public/com/chrynan/parcelable/parcelable-compose-android/)
- [parcelable-core-android-debug/](https://repo.repsy.io/mvn/chrynan/public/com/chrynan/parcelable/parcelable-core-android-debug/)
- [parcelable-core-android/](https://repo.repsy.io/mvn/chrynan/public/com/chrynan/parcelable/parcelable-core-android/)

The [Gradle module metadata](https://repo.repsy.io/mvn/chrynan/public/com/chrynan/parcelable/parcelable-core/0.8.0/parcelable-core-0.8.0.module) is missing the `android*Elements-published` variants, so upgrading to 0.8.0 results in Gradle selecting the JVM variant for Android builds, which is definitely broken.

**Comment by chRyNaN** [comment]
Good catch, I think I know what the issue is. Will try and get an update out today. https://github.com/chRyNaN/serialization-parcelable/blob/develop/parcelable-core/build.gradle.kts#L20

**Comment by chRyNaN** [comment]
@tadfisher Could you try again? It looks like the android artifacts are now available. This was the issue:

```kotlin
// Before:
androidTarget()

// After:
androidTarget {
        publishAllLibraryVariants()
}
```

**Comment by chRyNaN** [comment]
BTW JVM should not be broken, if it is please file an issue. But JVM doesn't have the Android components or functionality (Intent, Bundle, etc).

**Comment by tadfisher** [comment]
> But JVM doesn't have the Android components or functionality (Intent, Bundle, etc).

Right, so any Android source set depending on `parcelable-core` (expecting the Android variant) that uses the Android-specific APIs (`encodeToBundle`, etc) will fail to compile. I don't actually know if the JVM variant works on Android, to be clear.

Thank you for addressing this!
